# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

servicios:
  url:  /servicios
  param: { module: static, action: servicios }
  
quienessomos:
  url:  /quienes-somos
  param: { module: static, action: quienessomos }
  
dondeestamos:
  url:  /donde-estamos
  param: { module: static, action: dondeestamos }
  
corretaje:
  url:  /corretaje-de-propiedades
  param: { module: static, action: corretaje }
  
contacto:
  url:  /contacto
  param: { module: static, action: contacto }
  
sendmail:
  url: /sendmail
  param: { module: static, action: sendmail }

# default rules
homepage:
  url:   /
  param: { module: static, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
